import {StyleSheet} from 'react-native';
import {C} from './colors';

export const s = StyleSheet.create({
  safe: {flex: 1, backgroundColor: C.bg},
  spacer: {flex: 1},
  onboard: {
    flex: 1,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
    alignItems: 'center',
    padding: 28,
  },
  logo: {
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: '#0e3444',
    marginTop: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  house: {fontSize: 64, color: C.cyan},
  c: {position: 'absolute', fontWeight: 'bold'},
  brand: {fontSize: 30, fontWeight: 'bold', color: C.text, marginTop: 28},
  blue: {color: C.cyan},
  muted: {color: C.muted, fontSize: 13, lineHeight: 20},
  footer: {color: C.muted, fontSize: 10, marginTop: 16},
  header: {height: 84, flexDirection: 'row', alignItems: 'center', padding: 20},
  back: {fontSize: 38, color: C.text, marginRight: 16},
  title: {color: C.text, fontSize: 24, fontWeight: 'bold'},
  pad: {flex: 1, width: '100%', maxWidth: 520, alignSelf: 'center', padding: 20},
  label: {color: C.text, marginTop: 16, marginBottom: 6},
  input: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#21404e',
    color: C.text,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  btn: {
    height: 48,
    borderRadius: 12,
    backgroundColor: C.cyan,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  btnText: {fontWeight: 'bold', fontSize: 13, color: C.bg},
  tabs: {height: 64, backgroundColor: '#0a1b25', flexDirection: 'row'},
  tab: {flex: 1, alignItems: 'center', justifyContent: 'center'},
  tabText: {color: C.muted, fontSize: 10, textAlign: 'center'},
  section: {
    color: C.text,
    fontSize: 17,
    fontWeight: 'bold',
    marginTop: 22,
    marginBottom: 12,
  },
  tutor: {
    backgroundColor: C.card,
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    flexDirection: 'row',
    gap: 14,
  },
  avatar: {
    height: 32,
    width: 32,
    borderRadius: 16,
    backgroundColor: C.cyan,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigAvatar: {
    height: 56,
    width: 56,
    borderRadius: 28,
    backgroundColor: C.cyan,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {color: C.text, fontWeight: 'bold', fontSize: 16},
  star: {color: '#ffd75e', marginTop: 8},
  profile: {
    color: C.text,
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 12,
  },
  chip: {color: C.cyan, backgroundColor: C.card, padding: 12, borderRadius: 10},
  greeting: {color: C.text, fontSize: 20, fontWeight: 'bold'},
  card: {backgroundColor: C.card, borderRadius: 14, padding: 16, marginTop: 16},
  match: {color: C.text, fontSize: 24, fontWeight: 'bold', marginTop: 8},
});
