import { StyleSheet } from 'react-native';
import { C } from './colors';

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.bg },
  width: { width: '100%', maxWidth: 520, alignSelf: 'center' },
  body: { paddingHorizontal: 20, paddingBottom: 28 },
  text: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    lineHeight: 20,
    color: C.text,
  },
  muted: {
    fontFamily: 'Inter-Regular',
    color: C.muted,
    fontSize: 11,
    lineHeight: 19,
  },
  name: {
    fontFamily: 'Inter-SemiBold',
    color: C.text,
    fontSize: 14,
    lineHeight: 21,
  },
  heading: {
    fontFamily: 'Inter-Bold',
    color: C.text,
    fontSize: 22,
    lineHeight: 29,
  },
  section: {
    fontFamily: 'Inter-SemiBold',
    color: C.text,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 28,
    marginBottom: 12,
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  grow: { flex: 1 },
  card: {
    backgroundColor: C.card,
    borderColor: C.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  selected: { borderColor: C.cyan, backgroundColor: C.chip },
  divider: { height: 1, backgroundColor: C.border, marginVertical: 24 },
  center: { textAlign: 'center' },
  blue: { color: C.cyan },
  green: { color: C.green },
  danger: { color: C.danger },
  star: {
    fontFamily: 'Inter-SemiBold',
    color: C.yellow,
    fontSize: 11,
    marginTop: 12,
  },
  gap: { height: 16 },
  bigGap: { height: 32 },
  fieldGroup: { marginBottom: 14 },
  label: {
    fontFamily: 'Inter-Medium',
    color: C.text,
    fontSize: 12,
    marginBottom: 8,
  },
  inputRow: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 10,
  },
  input: {
    flex: 1,
    fontFamily: 'Inter-Regular',
    color: C.text,
    fontSize: 12,
    paddingVertical: 12,
    paddingHorizontal: 4,
    minHeight: 46,
  },
  multiline: { minHeight: 96, textAlignVertical: 'top' },
  btn: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: C.cyan,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginTop: 12,
  },
  outline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: C.cyan,
  },
  btnText: {
    fontFamily: 'Inter-Bold',
    fontSize: 13,
    color: C.bg,
    textAlign: 'center',
  },
  disabled: { opacity: 0.5 },
  chip: {
    minHeight: 30,
    borderRadius: 16,
    backgroundColor: C.chip,
    paddingHorizontal: 16,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipText: { fontFamily: 'Inter-SemiBold', color: C.cyan, fontSize: 10 },
  link: {
    fontFamily: 'Inter-SemiBold',
    color: C.cyan,
    fontSize: 11,
    lineHeight: 18,
  },
  linkControl: { minHeight: 40, justifyContent: 'center' },
  avatar: {
    height: 28,
    width: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontFamily: 'Inter-Bold', fontSize: 11, color: C.bg },
  empty: { paddingVertical: 36, alignItems: 'center', gap: 12 },
  error: {
    fontFamily: 'Inter-Regular',
    color: C.danger,
    fontSize: 12,
    lineHeight: 20,
    marginVertical: 8,
  },
  banner: { padding: 12, backgroundColor: C.card },
});
